title: "Zhenghao Yang"
description: "Undergraduate at  RUC. Research: Development Economics, Political Economy, Economic History"
url: "https://15haohao.github.io"
markdown: kramdown
theme: null
plugins: []
permalink: pretty